name: golangci-lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
     