on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: Test
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Test
      run:  go test -v -race
